# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carter Thayer
first_name: Carter
last_name: Thayer
email: carterwthayer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My name is Carter Thayer. I'm a software engineer from Ames, Iowa.
    I have been writing code for the past 8 years. I have experience with
    many areas of computer science and programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carterthayer.com" # the base hostname & protocol for your site
github_username:  carterthayer
linkedin_username:  carter-thayer-2155281a

# Build settings
markdown: kramdown
