# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carter Thayer
first_name: Carter
last_name: Thayer
email: carterwthayer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineer currently studying at Iowa State University.
  I like writing Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carterthayer.com" # the base hostname & protocol for your site
twitter_username: carterthayer
github_username:  carterthayer

# Build settings
markdown: kramdown
